AWSTemplateFormatVersion: '2010-09-09'

Parameters:

    ArtifactsS3Bucket:
      Type: String

    ArtifactsS3Prefix:
      Type: String

    PokemonStackName:
      Type: String

    BuildVersion:
      Type: String
      
    StageName:
      Type: String
      
Resources:

  Api:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Sub "${AWS::StackName}"
      Body:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub 's3://${ArtifactsS3Bucket}/${ArtifactsS3Prefix}/${BuildVersion}/build-artifacts/api-specification.yaml'

  ApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      Description: !Sub 's3://${ArtifactsS3Bucket}/${ArtifactsS3Prefix}/${BuildVersion}/api-specification/main.yaml'
      RestApiId: !Ref Api

  ApiStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      RestApiId: !Ref Api
      DeploymentId: !Ref ApiDeployment 
      StageName: !Sub '${StageName}'

  # APIGateway invoking Lambda permissions
  #----------------------------------------
  # AuthorizerLambdaPermission:
  #   Type: 'AWS::Lambda::Permission'
  #   Properties:
  #     Action: lambda:InvokeFunction
  #     FunctionName:
  #       Fn::ImportValue:
  #         !Sub "${MerchantStackName}-OpenApiAuthoriserLambda"
  #     Principal: apigateway.amazonaws.com
  #     SourceArn:
  #       Fn::Sub: "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*"

  PokemonLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::ImportValue:
          !Sub "${PokemonStackName}-ApiFunction"
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*"

Outputs:

  ApiId:
    Description: API ID
    Value: !Ref Api

  ApiUrl:
    Description: API URL
    Value: !Join
      - ''
      - - https://
        - !Ref Api
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com'
        - '/'
        - !Ref ApiStage